services:
  - type: web
    name: zenfeed-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false # set manually in Render dashboard
      - key: PYTHON_VERSION
        value: "3.10.0"
